# 基础配置
title: "我的个人主页"
description: "欢迎访问我的个人网站！"
baseurl: ""  # 如果站点在子目录（如 /blog），需填写子目录名
url: "https://cybervoyagerx.github.io"  # 替换为你的 GitHub Pages URL

# Jekyll 设置
theme: minima  # 使用默认主题（可替换为其他主题）
plugins:
  - jekyll-feed

# 自定义变量
author:
  name: "你的名字"
  email: "your@email.com"
  github: "yourusername"

# 导航菜单
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      nav: true  # 是否显示在导航栏

# 排除不需要处理的文件
exclude:
  - Gemfile
  - Gemfile.lock

# 添加以下配置
sass:
  sass_dir: assets/css
  style: compressed