title: VoyagerX's Blog
description: A tech blog about cybersecurity and coding
baseurl: "" 
url: "https://CyberVoyagerX.github.io"
theme: minima

# Plugins
plugins:
  - jekyll-feed

# Social media
twitter_username: yourtwitter
github_username: CyberVoyagerX

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/